os: unstable

environment:
  matrix:
    - nodejs_version: 9

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> package.json
  - app/node_modules -> app/package.json

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - npm i -g lerna
  - yarn

test_script:
  - node --version
  - lerna bootstrap && lerna run build
  - yarn package
  - yarn test
  - yarn test-e2e
